name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Or your desired .NET version

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Install Playwright browsers
        run: dotnet tool install --global playwright.cli && playwright install

      - name: Run Playwright tests
        run: dotnet test --configuration Release --filter TestCategory=Playwright # Or your test filter

      - name: Upload Playwright test results (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-results
          path: TestResults # Adjust path if needed